name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: mvn clean compile package
      
    - name: Get version from pom.xml
      id: get_version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: target/MCBDisenchant-*.jar
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## MCBDisenchant ${{ github.ref_name }}
          
          ### Features
          - GUI-based item disenchanting
          - Remove individual enchantments from items
          - Configurable GUI appearance and messages
          - MiniMessage support for rich text formatting
          - Sound effects for user feedback
          
          ### Installation
          1. Download the JAR file below
          2. Place it in your server's `plugins` folder
          3. Restart your server
          4. Configure the plugin in `plugins/MCBDisenchant/config.yml` if needed
          
          ### Usage
          - Use `/disenchant` while holding an enchanted item
          - Click on enchanted books in the GUI to remove specific enchantments
          
          ### Requirements
          - Minecraft 1.21.4
          - Paper/Spigot server
          - Java 21+
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 